before_script: bundle exec rake db:create db:schema:load
bundler_args: "--without assets:development:production"
cache: bundler
language: ruby
rvm:
  - 2.3.1
script:
  - bundle exec rake
  - bundle exec rubocop
sudo: false
